# Enhanced Configuration - Complete Requirements Coverage
# Date Range: December 2018 to January 2024
# All required sentiment sources and technical indicators

# Data Configuration - Complete Requirements
data:
  # Stock symbols for analysis
  stocks: ['AAPL', 'MSFT', 'GOOGL', 'AMZN', 'TSLA']
  
  # Complete date range covering major events (Dec 2018 - Jan 2024)
  start_date: '2018-12-01'
  end_date: '2024-01-31'
  
  # Data collection settings
  cache_data: true
  cache_enabled: true
  use_parallel: true
  
  # Complete sentiment sources as requested
  sentiment_sources:
    sec_edgar:
      enabled: true
      weight: 0.25
      reliability: 1.0
      description: 'SEC EDGAR filings'
    federal_reserve:
      enabled: true
      weight: 0.20
      reliability: 1.0
      description: 'Federal Reserve data and reports'
    investor_relations:
      enabled: true
      weight: 0.25
      reliability: 0.95
      description: 'Official investor relations data'
    bloomberg_twitter:
      enabled: true
      weight: 0.20
      reliability: 0.85
      description: 'Bloomberg Twitter news'
    yahoo_finance:
      enabled: true
      weight: 0.10
      reliability: 0.75
      description: 'Yahoo Finance news (optional)'
  
  # Complete technical indicators as requested
  technical_indicators:
    basic: ['Open', 'High', 'Low', 'Close', 'Volume']  # OHLCV
    moving_averages: [5, 10, 20, 50, 200]  # EMA periods
    rsi_periods: [14, 21]  # RSI
    macd_params: 
      fast: 12
      slow: 26
      signal: 9
    bollinger_periods: [20]  # For BBW (Bollinger Band Width)
    vwap_periods: [20, 50]  # VWAP
    lag_periods: [1, 2, 3, 5, 10, 20]  # Lag features
  
  # Company mapping for better sentiment relevance
  company_mapping:
    AAPL:
      name: 'Apple Inc'
      sector: 'Technology'
      keywords: ['apple', 'iphone', 'ipad', 'mac', 'ios', 'tim cook', 'cupertino']
      cik: '0000320193'
    MSFT:
      name: 'Microsoft Corporation'
      sector: 'Technology'
      keywords: ['microsoft', 'windows', 'office', 'azure', 'xbox', 'satya nadella']
      cik: '0000789019'
    GOOGL:
      name: 'Alphabet Inc'
      sector: 'Technology'
      keywords: ['google', 'alphabet', 'youtube', 'android', 'search', 'sundar pichai']
      cik: '0001652044'
    AMZN:
      name: 'Amazon.com Inc'
      sector: 'Technology'
      keywords: ['amazon', 'aws', 'prime', 'alexa', 'jeff bezos', 'andy jassy']
      cik: '0001018724'
    TSLA:
      name: 'Tesla Inc'
      sector: 'Technology'
      keywords: ['tesla', 'elon musk', 'electric vehicle', 'model s', 'model 3', 'model y']
      cik: '0001318605'

# Sentiment Analysis Configuration (Step 2)
sentiment:
  model_name: "ProsusAI/finbert"
  batch_size: 16
  confidence_threshold: 0.7
  relevance_threshold: 0.85
  quality_threshold: 0.7
  text_max_length: 512
  min_articles_for_sentiment: 3
  cache_results: true
  device: "auto"
  
  # Quality filters for FinBERT processing
  quality_filters:
    min_length: true
    language_filter: true
    relevance_check: true
    confidence_filter: true
    duplicate_filter: true

# Temporal Decay Configuration (Step 3)
temporal_decay:
  # Horizon-specific decay parameters
  lambda_5: 0.3    # Fast decay for 5-day horizon
  lambda_30: 0.1   # Medium decay for 30-day horizon
  lambda_90: 0.05  # Slow decay for 90-day horizon
  
  # Lookback windows
  lookback_days:
    5: 10    # 10-day lookback for 5-day prediction
    30: 30   # 30-day lookback for 30-day prediction
    90: 60   # 60-day lookback for 90-day prediction
  
  # Quality thresholds
  min_sentiment_count: 3
  min_confidence: 0.7

# Model Configuration (Steps 4-5)
model:
  # TFT Architecture
  hidden_size: 64
  attention_head_size: 4
  dropout: 0.3
  num_lstm_layers: 2
  
  # Training parameters
  learning_rate: 0.001
  batch_size: 32
  max_epochs: 50
  early_stopping_patience: 10
  gradient_clip_val: 1.0
  weight_decay: 1e-4
  
  # Model variants for benchmarking
  variants:
    - 'TFT-Temporal-Decay'     # Main model with temporal decay
    - 'TFT-Static-Sentiment'   # TFT with static sentiment
    - 'TFT-Numerical'          # TFT without sentiment
    - 'LSTM'                   # LSTM baseline

# Multi-Horizon Prediction Configuration
horizons: [5, 30, 90]  # 5-day, 30-day, 90-day predictions

# Target variables for investment decisions
targets:
  prediction_types:
    - 'returns'      # Continuous returns
    - 'direction'    # Binary direction (up/down)
    - 'volatility'   # Risk measure
  
  # Investment decision thresholds
  decision_thresholds:
    buy_threshold: 0.05    # 5% expected return for buy signal
    sell_threshold: -0.03  # -3% expected return for sell signal
    # Between these thresholds = hold

# Evaluation and Explainability Configuration (Step 6)
evaluation:
  # Statistical tests
  significance_level: 0.05
  min_observations: 30
  
  # Metrics to compute
  metrics: ['RMSE', 'MAE', 'MAPE', 'R2', 'directional_accuracy', 'sharpe_ratio']
  
  # Statistical tests for model comparison
  statistical_tests: ['wilcoxon', 'friedman', 'diebold_mariano']
  
  # Explainability features
  explainability:
    feature_importance: true
    attention_analysis: true
    sentiment_attribution: true
    temporal_contribution: true
    investment_reasoning: true

# Experiment Configuration
experiment:
  name: "Enhanced-Multi-Horizon-Sentiment-TFT"
  version: "v2.0"
  description: "Complete pipeline with all requirements: sentiment sources, technical indicators, temporal decay, multi-horizon prediction, and investment explainability"
  save_results: true
  save_intermediate_results: true
  create_report: true
  track_metrics: true
  save_predictions: true

# File Paths
paths:
  raw_data: 'data/raw'
  processed_data: 'data/processed'
  cache_dir: 'data/cache'
  results_dir: 'results'
  models_dir: 'results/models'
  plots_dir: 'results/plots'
  reports_dir: 'results/reports'
  
  # Dataset files
  enhanced_dataset: 'enhanced_combined_dataset.parquet'
  sentiment_features: 'sentiment_features.parquet'
  temporal_decay_features: 'temporal_decay_features.parquet'
  model_ready_data: 'model_ready_data.parquet'

# Data Quality Requirements
quality_requirements:
  min_trading_days: 250        # Minimum 1 year of data per symbol
  min_news_articles: 50        # Minimum articles per symbol
  max_missing_data_pct: 5      # Maximum 5% missing data
  min_sentiment_coverage: 0.8  # 80% of days should have sentiment data
  
  # Required feature coverage
  required_technical_indicators: ['EMA_20', 'RSI_14', 'MACD', 'BBW_20', 'VWAP_20']
  required_sentiment_sources: ['sec_edgar', 'federal_reserve', 'investor_relations', 'bloomberg_twitter']

# Performance and Hardware
performance:
  parallel_news_collection: true
  chunk_size: 1000
  memory_limit_mb: 4096
  num_workers: 4
  persistent_workers: true
  use_gpu: true
  mixed_precision: true

# Reproducibility
random_seed: 42

# Logging Configuration
logging:
  level: "INFO"
  save_logs: true
  log_file: "enhanced_experiment.log"
  console_output: true
  detailed_progress: true

# Error Handling
error_handling:
  continue_on_symbol_failure: true
  max_symbol_failures: 1
  retry_failed_symbols: true
  graceful_degradation: true
  fallback_to_mock_data: true

# Validation and Testing
validation:
  run_data_quality_checks: true
  validate_technical_indicators: true
  validate_sentiment_sources: true
  validate_date_coverage: true
  validate_feature_completeness: true