# Quick test configuration - minimal setup for fast testing
data:
  stocks: ['AAPL', 'MSFT']  # Just 2 stocks
  start_date: '2024-01-01'   # Shorter time period
  end_date: '2024-06-01'
  cache_data: true

sentiment:
  batch_size: 4
  confidence_threshold: 0.7
  relevance_threshold: 0.8
  sources: ['yahoo_finance_news']

temporal_decay:
  lambda_5: 0.3
  lambda_30: 0.1  
  lambda_90: 0.05
  lookback_days: {5: 10, 30: 30, 90: 60}

model:
  hidden_size: 32      # Smaller for faster training
  batch_size: 16
  max_epochs: 10       # Fewer epochs for testing
  early_stopping_patience: 5

training:
  cv_folds: 2          # Fewer folds for speed

horizons: [5, 30, 90]
random_seed: 42
